# NOTE: We use conda only for managing environments and
# installing special packages that cannot be installed by
# Poetry. Put all other dependencies in 'pyproject.toml'.
name: demo_project
channels:
  - conda-forge
  # Exclude default channels, as they may differ between users.
  - nodefaults
dependencies:
  - python=3.10.* 
  - mamba=1.3.*
  - pip=23.*  # Pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.3.2 # Must match the version of poetry you are using
  - conda-pack=0.6.0
  - conda-lock=1.4.0
  - yq=3.1.* # Used in bin/update-env.sh

# List target platforms for conda-lock
platforms:
  - linux-64